# Generated by Django 2.2.7 on 2019-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='lat',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='lon',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
